<?php
$title = 'Add new Locatiom';
$this->headTitle($title);
?>
<h1><?php $this->escapeHtml($title) ?></h1>
<?php echo $this->partial('blocks/navigation-buttons.phtml') ?>
<?php
// This provides a default CSS class and placeholder text for the title element:
$title = $form->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Location Title');

// This provides a default CSS class and placeholder text for the location element:
$long = $form->get('long');
$long->setAttribute('class', 'form-control');
$long->setAttribute('placeholder', 'Longitude');

$lat = $form->get('lat');
$lat->setAttribute('class', 'form-control');
$lat->setAttribute('placeholder', 'Latitude');

$type = $form->get('type');
$type->setAttribute('class', 'form-control');
$type->setAttribute('placeholder', 'Type');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('location', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">
        <?php echo $this->formLabel($title) ?>
        <?php echo $this->formElement($title) ?>
        <?php echo $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?php echo $this->formLabel($type) ?>
        <?php echo $this->formElement($type) ?>
        <?php echo $this->formElementErrors()->render($type, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('file')); ?>
        <?= $this->formElement($form->get('file')); ?>
        <?= $this->formElementErrors($form->get('file')); ?>
        <div class="hint">(PNG and JPG formats are allowed)</div>
    </div>
<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();