<?php
// module/Location/view/location/location/edit.phtml:

$title = 'Edit location';
$this->headTitle($title);
?>
<h1><?php $this->escapeHtml($title) ?></h1>
<?php
$title = $form->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Location title');

$long = $form->get('long');
$long->setAttribute('class', 'form-control');
$long->setAttribute('placeholder', 'Longitude');

$lat = $form->get('lat');
$lat->setAttribute('class', 'form-control');
$lat->setAttribute('placeholder', 'Latitude');

$type = $form->get('type');
$type->setAttribute('class', 'form-control');
$type->setAttribute('placeholder', 'Type');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('location', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="form-group">
        <?php echo $this->formLabel($title) ?>
        <?php echo $this->formElement($title) ?>
        <?php echo $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?php echo $this->formLabel($long) ?>
        <?php echo $this->formElement($long) ?>
        <?php echo $this->formElementErrors()->render($long, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?php echo $this->formLabel($lat) ?>
        <?php echo $this->formElement($lat) ?>
        <?php echo $this->formElementErrors()->render($lat, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?php echo $this->formLabel($type) ?>
        <?php echo $this->formElement($type) ?>
        <?php echo $this->formElementErrors()->render($type, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();