<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$title = 'My Locations';
$this->headTitle($title);


?>
<h1><?php $this->escapeHtml($title) ?></h1>
<?php echo $this->partial('blocks/navigation-buttons.phtml') ?>

<div id="map" style="height:500px;"></div>

<?php echo $this->partial('blocks/navigation-buttons.phtml') ?>


<script>
    var map;
    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            zoom: 4,
            center: new google.maps.LatLng(43.7384176, 7.4246158)
        });

        var iconBase = '<?php echo $this->basePath() . 'img/' ?>';
        var icons = {
            home: {
                icon: iconBase + 'home.png'
            },
            destination: {
                icon: iconBase + 'destination.png'
            },
            visited: {
                icon: iconBase + 'visited.png'
            }
        };

        var locations = JSON.parse('<?php echo $locations; ?>');
        var activeWindow = null;

        locations.forEach(function(location) {
            var infoContent = "<h3>" + location.title + "</h3>";
            if (location.file) {
                var imageBase = '<?php echo $this->basePath() . 'img/upload/' ?>';
                var imageUrl = imageBase+location.file;
                infoContent = infoContent + '<img src="' + imageUrl + '" height="250px"/>';
            }
            var locationInfoWindow = new google.maps.InfoWindow({
                content: infoContent
            });

            var marker = new google.maps.Marker({
                position: new google.maps.LatLng(location.lat, location.long),
                icon: icons[location.type].icon,
                clickable:true,
                map: map,
                infowindow: locationInfoWindow
            });

            google.maps.event.addListener(marker, 'click', function() {
                if (activeWindow) {
                    activeWindow.close();
                }
                this.infowindow.open(map, this);
                activeWindow = this.infowindow;
            });
        });
    }
</script>


<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYPYnMfO_k_eoKa1UkmmUt2To1INor0UE&callback=initMap">
</script>
